# Generated by Django 5.1.6 on 2025-03-25 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField(default=(1900, 1, 1))),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('salary', models.FloatField(null=True)),
                ('memo', models.TextField()),
                ('website', models.URLField(null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
