# Generated by Django 5.1.6 on 2025-03-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
                ('create_at', models.DateTimeField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
